#!/bin/bash
set -e

echo "Creating API user and required schemas"

psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} <<-SQL
  CREATE USER ${POSTGRES_API_USER} NOINHERIT NOSUPERUSER
  WITH PASSWORD ${POSTGRES_API_USER_PASSWORD};
  CREATE SCHEMA backend;
  CREATE SCHEMA api;
  GRANT USAGE ON SCHEMA api TO ${POSTGRES_API_USER};
SQL
